### PR TITLE
tic tac toe game using c lsnguage

### PR DESCRIPTION
**Pull request by prachi996**
please merge it.

### CODE REVIEW

**Review by amandeep2326 — CHANGES_REQUESTED** [review]
Pls maintain folder structure

**Comment by prachi996** [comment]
in which folder I have to shift this?

**Comment by amandeep2326** [comment]
You could shift it to DSA folder or CPP

**Comment by prachi996** [comment]
now is it ok.

**Comment by amandeep2326** [comment]
Yes Fine

**Pull request merged**
